# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: com.lucasdeeiroz.robotrunner
PackageVersion: 2.0.72
PackageLocale: en-US
Publisher: Lucas de Eiroz Rodrigues
PublisherUrl: https://github.com/lucasdeeiroz
PublisherSupportUrl: https://github.com/lucasdeeiroz/robot_runner/issues
PublisherContactUrl: https://github.com/lucasdeeiroz/robot_runner/issues
PackageName: Robot Runner
License: MIT
ShortDescription: A modern, cross-platform GUI for Robot Framework and Appium, designed to simplify test automation workflows.
ManifestType: defaultLocale
ManifestVersion: 1.10.0
